# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_read_binary_tree <- function(fileName, offset, globalNames, names, attributeNames, attributesAreNumeric) {
    .Call('_TreeNode_Rcpp_read_binary_tree', PACKAGE = 'TreeNode', fileName, offset, globalNames, names, attributeNames, attributesAreNumeric)
}

Rcpp_read_binary_trees <- function(fileName) {
    .Call('_TreeNode_Rcpp_read_binary_trees', PACKAGE = 'TreeNode', fileName)
}

Rcpp_read_nwka_string <- function(source, debug) {
    .Call('_TreeNode_Rcpp_read_nwka_string', PACKAGE = 'TreeNode', source, debug)
}

Rcpp_read_nwka_file <- function(fileName, debug) {
    .Call('_TreeNode_Rcpp_read_nwka_file', PACKAGE = 'TreeNode', fileName, debug)
}

Rcpp_read_nexus_file <- function(fileName, debug) {
    .Call('_TreeNode_Rcpp_read_nexus_file', PACKAGE = 'TreeNode', fileName, debug)
}

Rcpp_write_binary_trees <- function(trees, fileName, additionalData) {
    invisible(.Call('_TreeNode_Rcpp_write_binary_trees', PACKAGE = 'TreeNode', trees, fileName, additionalData))
}

Rcpp_begin_writing_binary_trees <- function(fileName) {
    .Call('_TreeNode_Rcpp_begin_writing_binary_trees', PACKAGE = 'TreeNode', fileName)
}

Rcpp_write_binary_tree <- function(tree, fileName, addresses) {
    .Call('_TreeNode_Rcpp_write_binary_tree', PACKAGE = 'TreeNode', tree, fileName, addresses)
}

Rcpp_finish_writing_binary_trees <- function(fileName, addresses, additionalData) {
    invisible(.Call('_TreeNode_Rcpp_finish_writing_binary_trees', PACKAGE = 'TreeNode', fileName, addresses, additionalData))
}

Rcpp_multiPhylo_to_string <- function(trees, nwka, singleQuoted) {
    .Call('_TreeNode_Rcpp_multiPhylo_to_string', PACKAGE = 'TreeNode', trees, nwka, singleQuoted)
}

Rcpp_multiPhylo_to_file <- function(trees, fileName, nwka, singleQuoted, append) {
    invisible(.Call('_TreeNode_Rcpp_multiPhylo_to_file', PACKAGE = 'TreeNode', trees, fileName, nwka, singleQuoted, append))
}

Rcpp_multiPhylo_to_nexus <- function(trees, fileName, translate, translateQuotes) {
    invisible(.Call('_TreeNode_Rcpp_multiPhylo_to_nexus', PACKAGE = 'TreeNode', trees, fileName, translate, translateQuotes))
}

